### ISSUE TITLE
titration

### ISSUE THREAD

**Issue by jwfoley** [lewisamarshall/ionize#68]
I think it would be more useful for Solution.titrate to return only a Solution containing the titrant and its concentration, rather than the complete titrated Solution. The original Solution might already contain the titrant so in the current scheme you have to subtract its titrated concentration from its original concentration (`spam.titrate(eggs, ham) - spam`). If this is changed, the existing functionality would still be available via `spam + spam.titrate(eggs, ham)`.

In a larger-scale change, it might be even more helpful if Solution.titrate could take a Solution as the titrant, and then express the result as a volume ratio. This would be practically useful in the lab because the titrant is likely some stock acid or base at a fixed concentration and what we want to know is the volume to use. It could also theoretically be useful if your titrant is a solution containing more than one ion for some reason, so the ratio of their concentrations is fixed and this doesn't necessasrily have to make the computation more difficult.

**Comment by lewisamarshall** [comment]
- ionize has hit 1.0, so the output of the titrate method can't be changed without breaking existing code. Subtraction is now implemented to make this easier.
- I like the idea of solutions as titrants. It would certainly make some problems easier, and it shouldn't be hard to implement.

**Comment by lewisamarshall** [comment]
#69 Is now up. It's a little messy.

**Comment by lewisamarshall** [comment]
#69 is now merged, with the ability to allow solutions to be titrated with other solutions. Please let me know if you encounter issues.
