### ISSUE TITLE
install biopython first

### ISSUE THREAD

**Issue by Gressling** [lewisamarshall/ionize#71]
dependency **error:
    from Bio import SeqUtils
    ModuleNotFoundError: No module named 'Bio'

solution:
pip install biopython
then pip install inonize

todo:
Update the setup readme

**Comment by lewisamarshall** [comment]
@Gressling The readme has been updated and the instructions for installing from source. In addition, the dependencies should install automatically if you install from `pip`. If you still have issues, please let me know!

Thank you for the feedback! ✨
