### ISSUE TITLE
can't multiply numpy.float64 by Solution

### ISSUE THREAD

**Issue by jwfoley** [lewisamarshall/ionize#77]
I can't multiply a `numpy.float64` × an `ionize.Solution`, even though I can multiply them in the other order, `ionize.Solution` × `numpy.float64`. This can come up when doing solution math because an `ionize.Solution` returns its concentrations as `numpy.float64` instead of a `float` if there is a multiplication operation in the line that instantiates it (maybe a separate bug?).

    Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
    [GCC 11.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ionize, numpy
    >>> 
    >>> hcl_10mM = ionize.Solution(['hydrochloric acid'], [0.1])
    >>> hcl_20mM = 2 * ionize.Solution(['hydrochloric acid'], [0.1])
    >>> 
    >>> hcl_10mM * 0.5 / hcl_10mM.concentration('hydrochloric acid')
    Solution(ions=['hydrochloric acid'], concentrations=[0.5])
    >>> 0.5 / hcl_10mM.concentration('hydrochloric acid') * hcl_10mM
    Solution(ions=['hydrochloric acid'], concentrations=[0.5])
    >>> hcl_20mM * 0.5 / hcl_20mM.concentration('hydrochloric acid')
    Solution(ions=['hydrochloric acid'], concentrations=[0.5])
    >>> 0.5 / hcl_20mM.concentration('hydrochloric acid') * hcl_20mM
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: unsupported operand type(s) for *: 'float' and 'Ion'
    >>> 
    >>> type(hcl_10mM.concentration('hydrochloric acid'))
    <class 'float'>
    >>> type(hcl_20mM.concentration('hydrochloric acid'))
    <class 'numpy.float64'>
    >>> 
    >>> hcl_10mM * 2
    Solution(ions=['hydrochloric acid'], concentrations=[0.2])
    >>> 2 * hcl_10mM
    Solution(ions=['hydrochloric acid'], concentrations=[0.2])
    >>> hcl_10mM * numpy.float64(2)
    Solution(ions=['hydrochloric acid'], concentrations=[0.2])
    >>> numpy.float64(2) * hcl_10mM
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: unsupported operand type(s) for *: 'float' and 'Ion'

**Comment by lewisamarshall** [comment]
Fixed with #84.
