### ISSUE TITLE
I cannot install ionize from PyPI successfully

### ISSUE THREAD

**Issue by Irony-Bearheart** [lewisamarshall/ionize#78]
I'm using _python 3.11.4_ on _Windows 10_, and _pip 23.1.2_ in my _venv_ at _E:\chemistrymodules\ionize\venv_ (as you will see below)
When I type `pip install ionize` in my cmd terminal, I am always imformed that it's not successfully installed.

Here is the output:

 

> Collecting ionize
> 
>   Using cached ionize-1.2.0.tar.gz (39 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [26 lines of output]
>       Traceback (most recent call last):
>         File "E:\chemistrymodules\ionize\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>           main()
>         File "E:\chemistrymodules\ionize\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "E:\chemistrymodules\ionize\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^
>         File "%temp%\pip-build-env-dkfhb51p\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=['wheel'])
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "%temp%\pip-build-env-dkfhb51p\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
>           self.run_setup()
>         File "%temp%\pip-build-env-dkfhb51p\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
>           super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
>         File "%temp%\pip-build-env-dkfhb51p\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
>           exec(code, locals())
>         File "<string>", line 11, in <module>
>         File "%temp%\pip-install-io6iwx1a\ionize_02371c13d70e4ce490ba5db708c6e8e2\ionize\__init__.py", line 14, in <module>
>           from .Solvent import Aqueous
>         File "%temp%\pip-install-io6iwx1a\ionize_02371c13d70e4ce490ba5db708c6e8e2\ionize\Solvent.py", line 4, in <module>
>           from .constants import gas_constant, reference_temperature, \
>         File "%temp%\pip-install-io6iwx1a\ionize_02371c13d70e4ce490ba5db708c6e8e2\ionize\constants.py", line 24, in <module>
>           import numpy as np
>       ModuleNotFoundError: No module named 'numpy'
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
How can I install it properly (I'd prefer using _pip_ instead of _conda_ or something like that)?

**Comment by Irony-Bearheart** [comment]
Those `%temp%` means the same as it means in Windows terminal.

**Comment by Irony-Bearheart** [comment]
Those `%temp%` means the same as it means in Windows terminal.(sorry for those closing and reopening)

**Comment by Irony-Bearheart** [comment]
This problem could be solved by installing requirements in advance.
However, I'll let this issue open until somgone fix it in _pypi.org_.

**Comment by lewisamarshall** [comment]
This issue should be fixed with the 1.5.1 release. Thanks for the feedback!

**Comment by Irony-Bearheart** [comment]
Thank you.
